version: '3.8'

services:
  multi-link:
    image: automacaodebaixocusto/multi-link:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == worker
      labels:
        # Habilitar Traefik
        - "traefik.enable=true"
        
        # Router principal
        - "traefik.http.routers.multi-link.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.multi-link.entrypoints=websecure"
        - "traefik.http.routers.multi-link.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.multi-link.service=multi-link-service"
        
        # Router para www
        - "traefik.http.routers.multi-link-www.rule=Host(`www.${DOMAIN}`)"
        - "traefik.http.routers.multi-link-www.entrypoints=websecure"
        - "traefik.http.routers.multi-link-www.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.multi-link-www.service=multi-link-service"
        
        # Router para API
        - "traefik.http.routers.multi-link-api.rule=Host(`${DOMAIN}`) && PathPrefix(`/api/`)"
        - "traefik.http.routers.multi-link-api.entrypoints=websecure"
        - "traefik.http.routers.multi-link-api.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.multi-link-api.service=multi-link-service"
        - "traefik.http.routers.multi-link-api.middlewares=api-rate-limit"
        
        # Router para autenticação
        - "traefik.http.routers.multi-link-auth.rule=Host(`${DOMAIN}`) && PathPrefix(`/api/auth/`)"
        - "traefik.http.routers.multi-link-auth.entrypoints=websecure"
        - "traefik.http.routers.multi-link-auth.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.multi-link-auth.service=multi-link-service"
        - "traefik.http.routers.multi-link-auth.middlewares=auth-rate-limit"
        
        # Middlewares de segurança
        - "traefik.http.middlewares.security-headers.headers.frameDeny=true"
        - "traefik.http.middlewares.security-headers.headers.contentTypeNosniff=true"
        - "traefik.http.middlewares.security-headers.headers.browserXssFilter=true"
        - "traefik.http.middlewares.security-headers.headers.referrerPolicy=strict-origin-when-cross-origin"
        - "traefik.http.middlewares.security-headers.headers.customRequestHeaders.X-Forwarded-Proto=https"
        
        # Middleware de compressão
        - "traefik.http.middlewares.compress.compress=true"
        
        # Rate limiting geral
        - "traefik.http.middlewares.rate-limit.ratelimit.average=50"
        - "traefik.http.middlewares.rate-limit.ratelimit.burst=100"
        
        # Rate limiting para API
        - "traefik.http.middlewares.api-rate-limit.ratelimit.average=10"
        - "traefik.http.middlewares.api-rate-limit.ratelimit.burst=20"
        
        # Rate limiting para autenticação
        - "traefik.http.middlewares.auth-rate-limit.ratelimit.average=2"
        - "traefik.http.middlewares.auth-rate-limit.ratelimit.burst=5"
        
        # Configuração do serviço
        - "traefik.http.services.multi-link-service.loadbalancer.server.port=3000"
        - "traefik.http.services.multi-link-service.loadbalancer.healthcheck.path=/api/health"
        - "traefik.http.services.multi-link-service.loadbalancer.healthcheck.interval=30s"
        - "traefik.http.services.multi-link-service.loadbalancer.healthcheck.timeout=5s"
        - "traefik.http.services.multi-link-service.loadbalancer.healthcheck.scheme=http"
    
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - EMAIL_SERVER_HOST=${EMAIL_SERVER_HOST}
      - EMAIL_SERVER_PORT=${EMAIL_SERVER_PORT}
      - EMAIL_SERVER_USER=${EMAIL_SERVER_USER}
      - EMAIL_SERVER_PASSWORD=${EMAIL_SERVER_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
    
    networks:
      - network_public

networks:
  network_public:
    external: true
    name: network_public
