version: '3.8'

services:
  postgres:
    image: postgres:16
    command: postgres -c 'max_connections=200' -c 'shared_buffers=256MB'
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: multilink
      PGDATA: /data/postgres/pgdata
    volumes:
      - type: bind
        source: /mnt/data/postgres
        target: /data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - network_public

networks:
  network_public:
    external: true
    name: network_public